# Generated by Django 3.1.7 on 2021-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingatlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(max_length=30)),
                ('méret', models.CharField(max_length=30)),
                ('cím', models.CharField(max_length=50)),
                ('ár', models.CharField(max_length=30)),
                ('szoba', models.CharField(max_length=30)),
                ('erkély', models.CharField(max_length=30)),
                ('elérhetőség', models.CharField(max_length=30)),
                ('kép', models.ImageField(upload_to='pics')),
            ],
            options={
                'verbose_name': 'ingatlan',
                'verbose_name_plural': 'ingatlanok',
            },
        ),
    ]
