# Generated by Django 3.1.7 on 2021-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingatlan', '0002_auto_20210426_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingatlan',
            name='kép',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
