# Generated by Django 3.1.7 on 2021-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingatlan', '0004_auto_20210426_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingatlan',
            name='kép',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
