# Generated by Django 3.1.7 on 2021-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingatlan', '0005_auto_20210426_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingatlan',
            name='árm2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
