# Generated by Django 3.1.7 on 2021-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingatlan', '0006_ingatlan_árm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingatlan',
            name='elértípus',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingatlan',
            name='elérhetőség',
            field=models.CharField(max_length=50),
        ),
    ]
